### ISSUE TITLE
The deploy target version is too high in the podspec

### ISSUE THREAD

**Issue by Whirlwind** [guillermomuntaner/Burritos#10]
The deployment target seems too high:
```
  s.ios.deployment_target = '13.0'
  s.osx.deployment_target = '10.15'
  s.tvos.deployment_target = '13.0'
  s.watchos.deployment_target = '6.0'
```

The wrapper is a compiler feature, not the runtime. Is it right?

**Comment by lammertw** [comment]
I'm running into the same problem. And the `DynamicUIColor` even has explicit support for versions before iOS 13. So why is the minimum target set to iOS 13?

**Comment by RomanPodymov** [comment]
Hello @Whirlwind 
Check the latest deployment targets:
```
s.ios.deployment_target = '8.0'
s.osx.deployment_target = '10.10'
s.tvos.deployment_target = '9.0'
s.watchos.deployment_target = '2.0'
```
However v.0.0.3 is not available via CocoaPods. 
@guillermomuntaner Could you please release v.0.0.3?

**Comment by guillermomuntaner** [comment]
Had issues with CocoaPods, will try again.

**Comment by guillermomuntaner** [comment]
@Whirlwind @lammertw @RomanPodymov just pushed 0.0.3 to cocoapods!
